### PR TITLE
Update intel-mkl-src requirement

### PR DESCRIPTION
**Pull request by ethanhs**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thank you. Please check the error on Travis CI.

**Comment by ethanhs** [comment]
Hmm it seems that it is getting a 404 when trying to download the mkl library from S3. Perhaps @termoshtt would know more (hopefully the ping is ok!)

**Comment by ethanhs** [comment]
Hi @IvanUkhov any chance you could take a look at this? I *think* it should just take re-running CI and it should be fine to merge.

**Comment by IvanUkhov** [comment]
Hi, sorry! It looks like Travis CI is no longer an option. It is in read-only mode. We should switch to GitHub Workflows.

**Comment by IvanUkhov** [comment]
OK, I have switched over to Actions now.

This does not pass the compilation step. Please open a new PR and see for yourself. (I merged without checking, but then force-pushed to undo, as it started to fail.)

**Comment by ethanhs** [comment]
Thanks for taking a look, odd that it didn't work, I'll dig into it.

**Pull request merged**
