### PR TITLE
Update openblas-src to 0.10

### PR DESCRIPTION
**Pull request by maoe**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thank you. Would you be able to update `lapack-src` too?

**Comment by bluss** [comment]
Hi. Just a question (don't want to stop anything). Is there a reason openblas-src is getting bumps in the 0.x version? This causes incompatible version number upgrades in blas-src and those that depend on blas-src (causing incompatible version bumps further downstream). Is this a necessary bump - or could openblas-src for example use version 0.10.1 the next time, to avoid it?

**Comment by IvanUkhov** [comment]
@termoshtt, what is your opinion on the versioning of `openblas-src`?

**Comment by termoshtt** [comment]
In my understanding, we keep the minor version (0.10) unless `features` in Cargo.toml and ABI of BLAS and LAPACK are kept. 0.10.2 includes large changes around the Fortran compiler detection sneaking https://github.com/blas-lapack-rs/openblas-src/pull/47 , but it only bump up patch version.

**Comment by bluss** [comment]
Thanks for the info. I guess I was also ignorant of what goes into the openblas-src releases :slightly_smiling_face: Nice job. Maybe it would be possible for blas-src to match with several openblas-src versions? I don't know if that can be practical.

**Comment by maoe** [comment]
> Would you be able to update lapack-src too?

Sure, will do.

**Comment by maoe** [comment]
Done https://github.com/blas-lapack-rs/lapack-src/pull/5

**Comment by maoe** [comment]
BTW, current version of boas-src is compatible with openblas-src 0.9 and 0.10. So technically speaking it should be possible to specify `>= 0.9, < 0.11`, which is a common practice in the Haskell community to support a wider range of dependencies. But as far as I can see it's rare to see this kind of version bounds in the Rust community. Why is that?

**Comment by bluss** [comment]
@maoe I think the reason is that cargo will always pick the newest version. One could imagine cargo trying to pick the "best" version in that range to get all crates in a project to build, but it doesn't do that, if I understand correctly.

**Comment by maoe** [comment]
Ah I see. Haskell's cabal tries to solve the version constraints then pick the latest versions (this is what you called the "best", I think) amongst the possible solutions.

**Comment by IvanUkhov** [comment]
Thank you!

**Pull request merged**
